version: '2'
services:
  redwood-auth-server:
    container_name: redwood-auth-server
    image: redwood-auth-server
    ports:
    - "8443:8443"
    - "8543:8543"
#    - "8000:8000"
    depends_on:
      - redwood-auth-db
  redwood-auth-db:
    container_name: redwood-auth-db
    image: postgres
    volumes:
    - ./conf/auth-schema-postgresql.sql:/docker-entrypoint-initdb.d/dcc-auth-db.sql
    - ./conf/pg_hba.conf:/etc/postgres/9.6/main/pg_hba.conf
  redwood-metadata-server:
    container_name: redwood-metadata-server
    image: redwood-metadata-server
    ports:
    - "8444:8444"
    - "8544:8544"
#    - "8001:8000"
    depends_on:
    - redwood-metadata-db
    - redwood-auth-server
  redwood-metadata-db:
    container_name: redwood-metadata-db
    image: mongo
  redwood-storage-server:
    container_name: redwood-storage-server
    image: redwood-storage-server
    ports:
    - "5431:5431"
#    - "8002:8000"
    volumes:
    - ./conf/application.storage.properties:/dcc/conf/application.properties
    - ~/.aws/credentials:/root/.aws/credentials
    depends_on:
    - redwood-auth-server
    - redwood-metadata-server
