version: '2'
services:
  ucsc-auth-server:
    container_name: ucsc-auth-server
    image: ucsc-auth-server
    ports:
    - "8443:8443"
    - "8543:8543"
    - "8000:8000"
    volumes:
    - ./conf/wrapper.auth.conf:/dcc/dcc-auth-server/conf/wrapper.conf
    - ./../ssl/artifacts:/dcc/conf/ssl
    environment:
    - UCSC_STORAGE_AUTH_DB=jdbc:postgresql://ucsc-auth-db
    - UCSC_STORAGE_TRUSTSTORE_PASSWORD=${TRUSTSTORE_PASSWORD}
    - UCSC_STORAGE_KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
    depends_on:
      - ucsc-auth-db
  ucsc-auth-db:
    container_name: ucsc-auth-db
    image: postgres
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}
    volumes:
    - ./conf/auth-schema-postgresql.sql:/docker-entrypoint-initdb.d/dcc-auth-db.sql
    - ./conf/pg_hba.conf:/etc/postgres/9.6/main/pg_hba.conf
  ucsc-metadata-server:
    container_name: ucsc-metadata-server
    image: ucsc-metadata-server
    ports:
    - "8444:8444"
    - "8544:8544"
    - "8001:8000"
    volumes:
    - ./conf/wrapper.metadata.conf:/dcc/dcc-metadata-server/conf/wrapper.conf
    - ./../ssl/artifacts:/dcc/conf/ssl
    environment:
    - UCSC_STORAGE_METADATA_DB=mongodb://ucsc-metadata-db:27017
    - UCSC_STORAGE_TRUSTSTORE_PASSWORD=${TRUSTSTORE_PASSWORD}
    - UCSC_STORAGE_KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
    - UCSC_STORAGE_AUTH_SERVER=https://ucsc-auth-server:8443
    - UCSC_STORAGE_METADATA_CLIENT_ID=metadata
    - UCSC_STORAGE_METADATA_CLIENT_SECRET=${METADATA_CLIENT_SECRET}
    depends_on:
    - ucsc-metadata-db
    - ucsc-auth-server
  ucsc-metadata-db:
    container_name: ucsc-metadata-db
    image: mongo
    ports:
    - "27017:27017"
  ucsc-storage-server:
    container_name: ucsc-storage-server
    image: ucsc-storage-server
    ports:
    - "5431:5431"
    - "8002:8000"
    volumes:
    - ./conf/wrapper.storage.conf:/dcc/dcc-storage-server/conf/wrapper.conf
    - ./../ssl/artifacts:/dcc/conf/ssl
    environment:
    - UCSC_STORAGE_TRUSTSTORE_PASSWORD=${TRUSTSTORE_PASSWORD}
    - UCSC_STORAGE_KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
    - UCSC_STORAGE_S3_BUCKET=beni-dcc-storage-dev
    - UCSC_STORAGE_AUTH_SERVER=https://ucsc-auth-server:8443
    - UCSC_STORAGE_METADATA_SERVER=https://ucsc-metadata-server:8444
    - UCSC_STORAGE_STORAGE_CLIENT_ID=storage
    - UCSC_STORAGE_STORAGE_CLIENT_SECRET=${STORAGE_CLIENT_SECRET}
    - UCSC_STORAGE_AWS_ACCESS_KEY=AKIAJHJOHQLZFOXLADWA
    - UCSC_STORAGE_AWS_SECRET_KEY=${AWS_SECRET_KEY}
    - UCSC_STORAGE_AWS_ENCRYPTION_KEY_ID=38a0e264-f28e-469f-86aa-c87dbfec3270
    - UCSC_STORAGE_S3_ENDPOINT=s3-us-west-2.amazonaws.com
    depends_on:
    - ucsc-auth-server
    - ucsc-metadata-server
